# Generated by Django 3.2.3 on 2021-05-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'permissions': [('can_view_non_moderated_quotes', 'Can_view_non_moderated_quotes')]},
        ),
    ]
