# Generated by Django 3.2.3 on 2021-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='status',
        ),
        migrations.AddField(
            model_name='quote',
            name='is_moderated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
