# Generated by Django 3.2.3 on 2021-05-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_quote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sum_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
