# Generated by Django 3.2.3 on 2021-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210527_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
